### PR TITLE
Fix checkbox event firing twice

### LINKED ISSUE #1471: Checkbox's onChange is triggered twice for a click
**Describe the bug**
When we click on the checkbox the onChange is triggered twice

**Expected behavior**
To be triggered only once per user interaction.

**Screenshots**
N/A

**Cosmos version:**
0.14.1

**Additional context**
Seems onChange is called by the onClick of the input & label of the component

### PR DESCRIPTION
**Pull request by francocorreasosa**
Fixes #1471 

We were passing the onChange event to both the option (label) and the checkbox itself. This caused the event to fire two times when the checkbox was toggled, since the label also fires it. Removing the event from the label solves the issue since now the checkbox is the only component providing this event.

### CODE REVIEW

**Comment by landitus** [comment]
- Is there any test (better than the one we deleted) we should have for the checkbox?
- @siddharthkp 	can you review?

**Comment by francocorreasosa** [comment]
@landitus We have the new one here: https://github.com/auth0/cosmos/blob/master/internal/test/integration/atoms/checkbox.test.js

**Comment by landitus** [comment]
Thanks @francocorreasosa 	I've missed that :) 

Then it's review and merge!

**Comment by siddharthkp** [comment]
Just saw the `🚨hi priority` on this. We can merge this PR (I've tested that it works) and continue to improve the code.

File: core/components/atoms/checkbox/checkbox.js [hunk 1]
```diff
@@ -14,7 +15,11 @@ const justifyContent = {
 }
 
 const Checkbox = props => (
-  <Checkbox.Option readOnly={props.readOnly} {...Automation('checkbox')} {...props}>
+  <Checkbox.Option
+    readOnly={props.readOnly}
+    {...Automation('checkbox')}
+    {...exclude('onChange', props)}
```
[the remark this answers is not in the document]
Comment (francocorreasosa) [reply core/components/atoms/checkbox/checkbox.js]: Nope, we're still passing it to the checkbox itself:
https://github.com/auth0/cosmos/blob/3ee1da38c0ffe14c94285f30c4ff56806c86f27a/core/components/atoms/checkbox/checkbox.js#L29

File: core/components/atoms/checkbox/checkbox.js [hunk 2]
```diff
@@ -18,7 +18,12 @@ const Checkbox = props => (
   <Checkbox.Option
     readOnly={props.readOnly}
     {...Automation('checkbox')}
-    {...exclude('onChange', props)}
+    {
+      // Prevent passing the onChange handler
+      // both to the label and the checkbox.
+      // See: https://github.com/auth0/cosmos/pull/1473
+      ...exclude('onChange', props)
```
Comment (siddharthkp) [inline core/components/atoms/checkbox/checkbox.js]: 👎 Still no clue what's going on 

> See: https://github.com/auth0/cosmos/pull/1473

lol @ recursion

Repeating myself:

> Just saw the `🚨hi priority` on this. We can merge this PR (I've tested that it works) and continue to improve the code.

Comment (francocorreasosa) [reply core/components/atoms/checkbox/checkbox.js]: Commented it in the body of the PR. The recursion is intentional and is intended for future reference, as we've been doing since a couple of months.

Comment (siddharthkp) [reply core/components/atoms/checkbox/checkbox.js]: Oops sorry, didn't read the description. Honest mistake

Comment (francocorreasosa) [reply core/components/atoms/checkbox/checkbox.js]: np, added it a couple minutes ago. It wasn't there before.

**Comment by siddharthkp** [comment]
> We were passing the onChange event to both the option (label) and the checkbox itself.

Should we pass props down to label at all? The label is just text, any additional props given by the user are meant for the input

**Comment by francocorreasosa** [comment]
Okay, sounds good. Let's keep just `readOnly` and `id` then.

**Comment by siddharthkp** [comment]
Does the `id` get applied to both label and input? If yes, we should pick one - the input I think

**Comment by francocorreasosa** [comment]
Done. Merging 👍
